# Default values for novosga.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

db:
  replicas: "1"
  image: "mysql:5.7"
  cpuRequest: "0.3"
  memoryRequest: "512Mi"
  cpuLimit: "0.5"
  memoryLimit: "512Mi"
  service:
    type: "ClusterIP"
    port: "3306"
  secret:
    MYSQL_USER: "novosga"
    MYSQL_DATABASE: "novosga2"
    MYSQL_ROOT_PASSWORD: "MySQL_r00t_P4ssW0rd!"
    MYSQL_PASSWORD: "MySQL_App_P4ssw0rd!"
  configMap:
    # Set TimeZone
    TZ: "America/Sao_Paulo"
app:
  replicas: 1
  image: "novosga/novosga:latest"
  cpuRequest: "0.3"
  memoryRequest: "256Mi"
  cpuLimit: "0.5"
  memoryLimit: "512Mi"
  containersPort:
    - 80
    - 2020
  service:
    nodePort: 30000
  secret:
    # default admin user
    NOVOSGA_ADMIN_USERNAME: "admin"
    NOVOSGA_ADMIN_PASSWORD: "123456"
    NOVOSGA_ADMIN_FIRSTNAME: "Administrator"
    NOVOSGA_ADMIN_LASTNAME: "Global"
    # database connection
    DATABASE_URL: "mysql://novosga:MySQL_App_P4ssw0rd!@db-svc:3306/novosga2?charset=utf8mb4&serverVersion=5.7"
  configMap:
    APP_ENV: "prod"
    # default unity
    NOVOSGA_UNITY_NAME: "Minha Unidade"
    NOVOSGA_UNITY_CODE: "U01"
    # default no-priority
    NOVOSGA_NOPRIORITY_NAME: "Normal"
    NOVOSGA_NOPRIORITY_DESCRIPTION: "Serviço Normal"
    # default priority
    NOVOSGA_PRIORITY_NAME: "Prioridade"
    NOVOSGA_PRIORITY_DESCRIPTION: "Serviço prioriade"
    # default place
    NOVOSGA_PLACE_NAME: "Guiche"
    # Set TimeZone and locale
    TZ: "America/Sao_Paulo"
    LANGUAGE: "pt_BR"
