apiVersion: v1
kind: Service
metadata:
  name: {{ .Relase.Name }}-app-service
  labels: {{ include "novosga.app.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector: {{ include "novosga.app.labels" . | nindent 4 }}
  ports:
    - port: 80
      nodePort: {{ .Values.app.service.nodePort | default 30000 }}
