apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
spec:
  replicas: {{ .Values.app.replicas | default 1}}
  selector:
    matchLabels: {{ include "novosga.app.labels" . | nindent 6 }}
  template:
    metadata:
      name: app-pod
      labels: {{ include "novosga.app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: novosga-container
          image: {{ .Values.app.image | quote | default "novosga/novosga:latest" }}
          resources:
            requests:
              cpu: {{ .Values.app.cpuRequest | quote | default "0.3" }}
              memory: {{ .Values.app.memoryRequest | quote | default "256Mi" }}
            limits:
              cpu: {{ .Values.app.cpuLimit | quote | default "0.5" }}
              memory: {{ .Values.app.memoryLimit | quote | default "512Mi" }}
          ports:
            {{- range $index, $value := .Values.app.containersPort  }}
              - containerPort: {{ $value }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
      restartPolicy: Always
