apiVersion: v1
kind: Service
metadata:
  name: db-svc-headless
  labels: {{ include "novosga.db.statefulset.labels" . | nindent 4 }}  
spec:
  type: "None"
  selector: {{ include "novosga.db.statefulset.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.db.service.port | default "3306" }}