apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-db-statefulset"
spec:
  replicas: {{ .Values.db.replicas | default "1" }}
  selector:
    matchLabels: {{ include "novosga.db.statefulset.labels" . | nindent 6 }}
  template:
    metadata:
      name: db-pod
      labels: {{ include "novosga.db.statefulset.labels" . | nindent 8 }}
    spec:
      containers:
        - name: db-sga-container
          image: {{ .Values.db.image | quote | default "mysql:5.7" }}
          resources:
            requests:
              cpu: {{ .Values.db.cpuRequest | quote | default "0.3" }}
              memory: {{ .Values.db.memoryRequest | quote | default "512Mi" }}
            limits:
              cpu: {{ .Values.db.cpuLimit | quote | default "0.5" }}
              memory: {{ .Values.db.memoryLimit | quote | default "512Mi" }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
          envFrom:
            - configMapRef:
                name: db-configmap
            - secretRef:
                name: db-secret
      restartPolicy: Always
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc
